# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e75c50fd0741f5dddbf084302c94cac7752b5f0db4c9d671dde5d035b9ae4e5a5077da0f5443201adb4f93321fa16124159b3e5a8198ce0e0d8f13ea0a58653f

test:
  secret_key_base: 7fc2025a1aa67d84d6ec6570dbe788d46fcad8b7f9a11a03f06bb3a5fbe5b9e1321f604ecc31173ef2409f6d7d9674834967121b8fbccb4d9adbd727b168ad00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
